/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors')
module.exports = {
  content: [
    "components/**/*.{html,js,jsx,tsx,ts}",
    "app/**/**/**/*.{js,ts,jsx,tsx}", // <-- Add this line
    "pages/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {},
    zIndex: {
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      '60': '60',
      '70': '70',
      '80': '80',
      '90': '90',
      '99': '99',
      '100': '100',
      '101': '101',
      '102': '102',
      '999': '999',
      '1000': '1000',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: '#000',
      white: '#fff',
      primary: colors.blue,
      secondary: colors.sky,
      gray: colors.slate,
      gray2: colors.gray,
      slate: colors.slate,
      neutral: colors.neutral,
      zinc: colors.zinc,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      // 'dark' : colors.zinc,
      'dark': {
        // 50: '#d5dce9',
        50: '#b6bfd2',
        100: '#9ba6be',
        200: '#828b9d',
        300: '#677082',
        400: '#3d424d',
        500: '#282d36',
        600: '#1e2026',
        700: '#1b1d21',
        800: '#17181c',
        900: '#111217',
        // 900: '#131419'
      }
    }
  },
  plugins: [],
}
